### ISSUE TITLE
Discordブレイクアウトルームの実装

### ISSUE THREAD

**Issue by murasame29** [murasame29/hackathon-util#1]
## 機能
- 特定のチャネルに存在するユーザを別のVCチャンネルに分散させる
  - イメージはZoomのブレイクアウトルーム
  - 基点のチャネルはコマンドを入力したユーザが現在居るチャネル
  - etc..
## TODO:後で追記する

**Comment by nakedtatsuya** [comment]
## 仕様

### インターフェイス

- Discord  Bot としてサーバーにインストールする
- Botの`/`コマンドをベースにAPIを呼び出す形式を想定している
  - `/breakoutroom` 引数は２つ
    - `target`: ブレイクアウトルームに送り込む対象ユーザーとなるVCチャンネル。参加している人を全員振り分ける
    - `people`: 一部屋あたりの人数
    - `time-to-live`: ブレイクアウトルームの時間 `分単位（m）`で設定する

### 処理の流れ

- 対象VCチャンネルに参加している人数を `people` 引数で割って作成に必要なブレイクアウトルーム数を計算する
- VCチャンネルを作成する
  - チャンネル名は`breakout_{index}` 感じのイメージ
- 対象VCチャンネル参加しているユーザーを作成したブレイクアウトルームに振り分ける
  - 基本はランダム
  - 振り分け後、time-to-liveの計測開始
- time-to-liveの経過後、ブレイクアウトルームにいるメンバーを全員最初のVCに戻す
  - 作成したブレイクアウトルームを削除する
